apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: {{ include "coraza-operator.fullname" . }}-ruleset-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
    istio.io/rev: {{ .Values.istio.revision | quote }}
spec:
  hosts:
    - {{ include "coraza-operator.serviceFQDN" . }}
  ports:
    - number: 80
      name: http
      protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
  endpoints:
    - address: {{ include "coraza-operator.serviceFQDN" . }}
