apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ include "coraza-operator.fullname" . }}-ruleset-cache
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
    istio.io/rev: {{ .Values.istio.revision | quote }}
spec:
  host: {{ include "coraza-operator.serviceFQDN" . }}
  trafficPolicy:
    tls:
      mode: DISABLE
