apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "coraza-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
