apiVersion: v1
kind: Service
metadata:
  name: {{ include "coraza-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "coraza-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 18080
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.metrics.port }}
    {{- end }}
  selector:
    {{- include "coraza-operator.selectorLabels" . | nindent 4 }}
