openshift:
  enabled: true

metrics:
  # TODO: re-enable secure metrics with auth once ServiceMonitor is configured for authn/authz.
  secure: false
  serviceMonitor:
    enabled: true
    scheme: http


resources:
  limits:
    cpu: 30m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi
