# TODO: TLS
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: coraza-ruleset-cache
  namespace: coraza-system
  labels:
    istio.io/rev: "coraza"
spec:
  host: coraza-controller-manager.coraza-system.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
