apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: coraza
    app.kubernetes.io/managed-by: kustomize
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  name: coraza-system
