apiVersion: v1
kind: Service
metadata:
  name: coraza-controller-manager
  namespace: coraza-system
  labels:
    app.kubernetes.io/name: coraza
    app.kubernetes.io/managed-by: kustomize
    control-plane: coraza-controller-manager
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 18080
  selector:
    app.kubernetes.io/name: coraza
    control-plane: coraza-controller-manager
  type: ClusterIP
