apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: coraza-ruleset-cache
  namespace: coraza-system
  labels:
    istio.io/rev: "coraza"
spec:
  hosts:
    - coraza-controller-manager.coraza-system.svc.cluster.local
  ports:
    - number: 80
      name: http
      protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
  endpoints:
    - address: coraza-controller-manager.coraza-system.svc.cluster.local
