image:
  repository: ghcr.io/networking-incubator/coraza-kubernetes-operator
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi


metrics:
  enabled: true
  # TODO: re-enable secure metrics with auth once ServiceMonitor is configured for authn/authz.
  secure: false
  serviceMonitor:
    enabled: false

istio:
  revision: "coraza"

openshift:
  enabled: false

podSecurityStandard:
  version: latest # v1.35

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
imagePullSecrets: []

# Only works on 1.30.0 or Higher
# resizePolicy:
#   - resourceName: cpu
#     restartPolicy: NotRequired
#   - resourceName: memory
#     restartPolicy: NotRequired
