image:
  repository: ghcr.io/networking-incubator/coraza-kubernetes-operator
  tag: latest
  pullPolicy: IfNotPresent

# NOTE: HA Presently Not Supported:
#  https://github.com/networking-incubator/coraza-kubernetes-operator/issues/38
replicas: 1

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi


metrics:
  enabled: true
  # TODO: Enable secure metrics with auth once ServiceMonitor is configured for authn/authz
  # https://github.com/networking-incubator/coraza-kubernetes-operator/issues/88
  serviceMonitor:
    enabled: false

istio:
  revision: "coraza"

openshift:
  enabled: false

podSecurityStandard:
  version: latest  # v1.35

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
imagePullSecrets: []

resizePolicy:
  - resourceName: cpu
    restartPolicy: NotRequired
  - resourceName: memory
    restartPolicy: NotRequired
