image:
  repository: ghcr.io/networking-incubator/coraza-kubernetes-operator
  tag: latest
  pullPolicy: IfNotPresent

replicas: 1

resources:
  limits:
    cpu: 30m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 64Mi

metrics:
  enabled: true
  port: 8082
  servicePort: 8082
  secure: true
  serviceMonitor:
    enabled: false
    scheme: ""
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: false
    labels: {}
    tlsConfig:
      insecureSkipVerify: true

istio:
  revision: "coraza"

openshift:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
imagePullSecrets: []

resizePolicy:
  - resourceName: cpu
    restartPolicy: NotRequired
  - resourceName: memory
    restartPolicy: NotRequired
