apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coraza-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: coraza-controller-manager
subjects:
  - kind: ServiceAccount
    name: coraza-controller-manager
    namespace: coraza-system
